### ISSUE TITLE
这个项目是什么背景

### ISSUE THREAD

**Issue by vus520** [joyieldInc/predixy#1]
背后的公司、团队什么的

**Comment by joyield** [comment]
团队根据在一线互联网维护redis的丰富经验，为了系统的解决redis服务使用和维护的问题，准备推出一套完整的企业级系统解决方案，秉承redis的开源精神，系统及各组件都会开源，predixy便是其中组件之一。

**Comment by vus520** [comment]
666
是哪家公司呢，方便透露吗

**Comment by joyield** [comment]
我们是一家初创公司，从predixy中也可以看出，我们要做的是提供一种普适的企业级整体redis解决方案，不像twemproxy、codis、cerberus等这些由某个公司在使用过程中开源出来的产品，它们具有浓厚的所属公司的使用场景。目前公司网站还在建设当中，因此具体介绍信息的话也没有公布出来。
