### ISSUE TITLE
erlang redis 驱动auth失败

### ISSUE THREAD

**Issue by lubberland** [joyieldInc/predixy#10]
```
Command = "AUTH password\r\n",
gen_tcp:send(Socket, Command),
```
已验证过连redis-server上是可以的

连predixy报错如下：
`{error,{unexpected_data,{ok,"-ERR unknown command 'auth'\r\n"}}}`

是不是predixy对auth这块的解析和redis-server有区别？
还是auth的协议有变化？

**Comment by fortrue** [comment]
因为erlang的这个客户端发送AUTH请求用的是inline command的协议，predixy没有支持这个协议，https://github.com/joyieldInc/predixy/issues/9 也提到了这个问题
看来对auth这个命令我得在predixy里添加对inline command这种格式的支持

**Comment by lubberland** [comment]
哦 一开始没看#9  是一类问题，把redis源码那块的协议解析拿过来？

**Comment by fortrue** [comment]
不一样，predixy里协议解析的数据结构是为零拷贝而特别设计的。

**Comment by lubberland** [comment]
追求太高了。。。

**Comment by fortrue** [comment]
已支持AUTH命令通过inline command协议发送
https://github.com/joyieldInc/predixy/commit/345ff2c20f6ebdd1f7b55edb7e70b15381eceae2
