### ISSUE TITLE
predixy 是否能支持redis cluster下的muti-databases？

### ISSUE THREAD

**Issue by PPPPIU** [joyieldInc/predixy#105]
在使用harbor时，harbor默认配置会用到index为0、1、2、3的redis db，在使用predixy时，只有index0能正常连接，其余的db会报错 Failed to load and run worker pool: connect to redis server timeout: ERR invalid DB index，在使用client连接predixy后执行select 0能成功，select 1-3均报ERR invalid DB index。

**Comment by fortrue** [comment]
redis cluster只支持一个database
