### ISSUE TITLE
请问该项目是不继续维护了吗

### ISSUE THREAD

**Issue by aaa930811** [joyieldInc/predixy#131]

**Comment by fortrue** [comment]
在维护

**Comment by fortrue** [comment]
> > 在维护
> 
> 有预计支持5.0+吗

支持了，不过没开源出来

**Comment by ReasonDuan** [comment]
> > > 在维护
> > 
> > 
> > 有预计支持5.0+吗
> 
> 支持了，不过没开源出来

有计划什么时候开源最新版吗？

**Comment by fortrue** [comment]
> > > > 在维护
> > > 
> > > 
> > > 有预计支持5.0+吗
> > 
> > 
> > 支持了，不过没开源出来
> 
> 有计划什么时候开源最新版吗？

目前没有计划

**Comment by piaodazhu** [comment]
很棒的项目，可惜一直没有更新。作者的公司还好吗？predixy今天依然在为企业客户提供服务吗？

**Comment by fortrue** [comment]
> 很棒的项目，可惜一直没有更新。作者的公司还好吗？predixy今天依然在为企业客户提供服务吗？

依然在为企业客户提供商业服务中

**Comment by cex-trader** [comment]
我看到aws市场里面已经下架了，还在维护吗？

**Comment by fortrue** [comment]
> 我看到aws市场里面已经下架了，还在维护吗？

你怎么知道在aws市场上架过，aws那个国内的市场上架也没什么收益，项目当然一直在维护
