### ISSUE TITLE
执行select命令报错

### ISSUE THREAD

**Issue by wangking7811** [joyieldInc/predixy#132]
通过代理执行select 0 没有问题，但是执行select 1 报(error) ERR invalid DB index。
通过连接实际的redis集群，是可以执行成功的。

**Comment by fortrue** [comment]
看看predixy配置里的Databases是不是和redis的db数一致

**Comment by wangking7811** [comment]
看了源码发现在集群模式下，Databases只能是1，配置是不生效的

**Comment by fortrue** [comment]
redis集群也不支持多database啊，你这是个什么redis集群

**Comment by wangking7811** [comment]
抱歉，确认了下我连接的redis是主备模式，并不是集群模式
