### ISSUE TITLE
是否支持动态监听cluster.conf的ClusterServerPool.Services变化

### ISSUE THREAD

**Issue by omigaZ** [joyieldInc/predixy#137]
在k8s集群部署redis时，podIp变化之后我这里可以实时写入到cluster.conf中。请问predixy是否可以通过错误检测然后重新读取配置文件拉起proxy。

**Comment by caojiajun** [comment]
https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/redis-proxy-zh.md 这款proxy支持动态路由哦
