### ISSUE TITLE
More detailed cluster.conf parameters description 

### ISSUE THREAD

**Issue by markus9203902** [joyieldInc/predixy#16]
Hello, can anyone add to Wiki or project description more details about how these parameters affect the operation of predixy? 
*    MasterReadPriority 
*    StaticSlaveReadPriority 
*    DynamicSlaveReadPriority 
*    RefreshInterval 
*    ServerFailureLimit 
*    ServerRetryTimeout 

Also I'm wonder how proxy performs checks of cluster nodes and is it keeps keep-alive connection to them all the time.

**Comment by fortrue** [comment]
I'm sorry for English doc/config.md miss. Now, let me explain these parameters in here, maybe I will provide English doc/config.md later.

+ Static/Dynamic node
a node is static node be list in config file explict, opposite, a node is dynamic node when it not be list in config file but be discover by sentinel or other cluster nodes.

+ ReadPriority
predixy can dispatch readonly request to slave node, The 0 ReadPriority will disable node readable, The healthy node(s) with largest ReadPriority will accept all readonly requests, random dispatch for multi healthy nodes with same ReadPriority

+ RefreshInterval
predixy to refresh nodes info and slots info period

+ ServerFailureLimit
A redis server will be mark failure when request failure times meet ServerFailureLimit

+ ServerRetryTimeout
predixy try to reconnect a redis server who be marked failure every ServerRetryTimeout seconds until success

predixy choice a node random to execute CLUSTER NODES every RefreshInterval seconds, refresh the nodes and slots according the response

predixy keep keep-alive connections with redis server

**Comment by markus9203902** [comment]
@fortrue thank you for the reply, sky cleared for me in most, hope for others too. But why SlaveReadPriority is located in cluster config? 
Redis config says, that this parameter counts only in Sentinel mode:

"# The slave priority is an integer number published by Redis in the INFO output.
# It is used by Redis Sentinel in order to select a slave to promote into a
# master if the master is no longer working correctly."
# slave-priority 100 

So Predixy working with Redis Cluster mode also can consume the "slave-priority" values of slave nodes and route RO queries to them?

MasterReadPriority is still confusing. What key values in Redis cluster predixy reads to determine what portion of read queries should go to master? Or this option takes into account only when SlaveReadPriority set, thus if I set in some Redis nodes config "slave-priority" and they'll actually become slaves in the cluster, and set, let say, MasterReadPriority 50 and SlaveReadPriority 50, so Read queries will be router by predixy to cluster in 50/50 percentage to master and slave nodes?
And if I'll set MasterReadPriority 0, master nodes will be used for writes and updates only? 

Actually I'm going to use this project in kinda production and ready to contribute some docs here based on my experience.

**Comment by fortrue** [comment]
Don't confuse predixy Master/SlaveReadPriority and redis slave-priority, predixy DON‘T use slave-priority.
ReadPriority designed for read write split,
some cases

Master/SlaveReadPriority | Master | Slave1 | Slave2|Note
---|---|---|---|---
60/50|all requests|0 requests|0 requests|Master dead, read requests deliver to slave until master(maybe new master) alive
60/0|all requests|0 requests|0 requests|Master dead, all requests fail
50/50|all write requests, 33.33%read requests|33.33% read requests|33.33% read requests|
0/50|all write requests, 0 read requests|50% read requests|50% read requests|all slaves dead, all read requests fail
10/50|all write requests, 0 read requests|50% read requests|50% read requests|all slaves dead, read requests deliver to master

**Comment by markus9203902** [comment]
@fortrue great than you, now everything is clear with Cluster.conf. I'm going to sum these up in WIki on this weekend.

**Comment by fortrue** [comment]
@markus9203902 good job, welcome your contributor

**Comment by markus9203902** [comment]
Pull request to add doc file 
https://github.com/joyieldInc/predixy/pull/17
