### ISSUE TITLE
请问predixy存在和redis中的scan的方式一样获取分片集群的所有数据的命令吗

### ISSUE THREAD

**Issue by zoutao0909** [joyieldInc/predixy#174]
我想做数据迁移，但是我的集群是通过predixy中间件访问的，我不清楚应该如何获取到所有数据

**Comment by fortrue** [comment]
试试不就知道了，有的

**Comment by zoutao0909** [comment]
抱歉，可能是我没有描述清楚，通过predixy是可以使用scan，但是只能取到当前连接的某一个分片的数据，不能获取到整个分片集群的所有分片的所有数据，但是又没办法切换分片，请问这种情况下，有什么办法获取分片集群的所有数据吗，像这种分片集群部署在内网的情况，通过部署predixy的方式对外暴露服务，predixy存在切换连接分片的功能吗，不然的话在数据迁移的场景下，不管是通过psync还是通过scan方式都没办法准确拿到分片集群完整的数据，请问这种场景在使用predixy的情况下您这边有对应的解决办法吗
