### ISSUE TITLE
java如何使用

### ISSUE THREAD

**Issue by Neil-Zhou** [joyieldInc/predixy#18]
java如何连接并使用，可否有案例

**Comment by fortrue** [comment]
这个和语言无关的，直接用客户端连接即可使用，java常用的客户端是[Jedis](https://github.com/xetorthio/jedis)

**Comment by Neil-Zhou** [comment]
已经成功了，请问下，这个你们是否已用到生产了吗？QPS大概是多少呀

**Comment by fortrue** [comment]
用到生产了，QPS看一下[benchmark](https://github.com/joyieldInc/predixy/wiki/Benchmark)吧

**Comment by Neil-Zhou** [comment]
感谢感谢！
