### ISSUE TITLE
server group 线程安全问题

### ISSUE THREAD

**Issue by lee-qiu** [joyieldInc/predixy#181]
ServerGroup类add()/remove()方法会操作mServs数组，好像这个过程有加了父类mMtx锁，但是getMaster()/getServer()/方法访问没有加锁，是不是会带来数组越界访问的问题

**Comment by fortrue** [comment]
并不会，虽然这依赖于编译器和标准库的实现。

**Comment by lee-qiu** [comment]
测试取下标没有越界访问的问题，at() 方法才有越界检查
