### ISSUE TITLE
使用Redis桌面管理工具 RedisDesktopManager 无法连接Proxy暴露出来的端口

### ISSUE THREAD

**Issue by ouchuji** [joyieldInc/predixy#184]
问题复现过程如下：
1 K8S 搭建了 RedisCluster集群，Cluster的服务以Service的名称+ 端口暴露给客户端
2 需要从集群外部的网络访问到RedisCluster，由于RedisCluster重定向内部IP的问题，所以使用predixy来代理redis的流量
3 predixy 配置了RedisCluster的访问，并对外暴露端口
4 使用RedisDesktopManager 连接 predixy 暴露的端口，连接是可以成功，如下图
![image](https://github.com/joyieldInc/predixy/assets/11475541/57d1bafd-d314-473a-9af6-b739b2d7e4b1)
5 但是进去里面还是会有报错，报错的原因就是请求又被重定向集群中节点的内部ip地址了，这个就不是很符合预期了，按理说不应该被重定向的才对
![image](https://github.com/joyieldInc/predixy/assets/11475541/bb8a9813-624e-412e-b1a7-3beec1b2b1ce)

疑问：
predixy 暴露出的端口是不是不支持集群模式的连接请求，还是我的配置有问题导致的？

**Comment by fortrue** [comment]
你用的什么版本的Predixy，如果是用的开源版，那么现在规避不了这个问题。如果用的是免费版，那可以在配置里配上VirtualRedisHost参数来规避这个问题。

**Comment by ouchuji** [comment]
> 你用的什么版本的Predixy，如果是用的开源版，那么现在规避不了这个问题。如果用的是免费版，那可以在配置里配上VirtualRedisHost参数来规避这个问题。

免费版，好的，我看下

**Comment by ouchuji** [comment]
> 你用的什么版本的Predixy，如果是用的开源版，那么现在规避不了这个问题。如果用的是免费版，那可以在配置里配上VirtualRedisHost参数来规避这个问题。

请教下，这个是设置它返回的host，那么返回的port该如何自定义呢？我看它现在取得是Predixy它自己的端口

**Comment by ouchuji** [comment]
已经测试成功，感谢！
