### ISSUE TITLE
Could you provide more information regarding differences between different distributed redis solutions?

### ISSUE THREAD

**Issue by wooparadog** [joyieldInc/predixy#2]
Such as:

* Different feature supports.
* Supported platforms(cluster/Sentinel)
* Performance(there is `corvus` tag in this repo, but performance comparison lacks corvus)
* ...

**Comment by fortrue** [comment]
我先用中文快速说明一下你提到的问题。
predixy设计主要适用三个redis使用场景
+ 场景一：单一redis节点，主从结构，通过redis-sentinel来自动failover
+ 场景二：多个redis节点，主从结构，通过redis-sentinel来自动failover
+ 场景三：redis cluster模式

# 场景一
这是redis很常见的一种场景，因为很多时候单个redis就可以满足需求，然而redis-sentinel监控的高可用导致的主节点变化会给客户端带来麻烦，三种常见的解决方式是：

+ 客户端支持redis-sentinel，发现主从已经切换
+ LVS虚IP
+ 添加代理层，代理通过redis-sentinel发现主从切换
三种方式比较而言添加代理层实施起来最容易，客户端支持不太可控，而且对于第三方的应用我们可能还无法实现；第二种方式部署起来麻烦。
predixy在这种场景下就等同于单个的redis实例。事务、阻塞式命令、发布订阅、脚本、多数据库等全支持。

# 场景二
这种场景就是twemproxy最常用的场景，只不过twemproxy不支持自动通过redis-sentinel来发现。predixy也支持这种场景，但是没有提供像twemproxy那么多的hash和distribution策略，从设计上来讲也不推荐使用这种方式，这种场景绝大部分需求redis cluster都可以满足。

# 场景三
redis cluster模式，在这种场景下，predixy和corvus、redis-cerberus等代理是一样的，支持redis cluster特定的MOVE/ASK等操作。predixy这时依然支持阻塞式命令、发布订阅、脚本等功能。

关于性能对比，我后来测了corvus，和twemproxy差不多。

**Comment by wooparadog** [comment]
嗯. 我看 readme 是英文的就用英文问了. 多谢回答.
