### ISSUE TITLE
Bug in handling offline shard 

### ISSUE THREAD

**Issue by markus9203902** [joyieldInc/predixy#21]
Hello! I guess I've faced a bug while testing the Predixy with redis-4.0.6.

I

Steps to reproduce:
1) Set up 3 - nodes Redis cluster, no replicas, masters only
2) Set up Predixy on each nodes with Redis cluster, to make a cross-connections. 
Direct each Predixy to three Redis nodes.
3) Turn off the server with one of the Redis nodes by power button (turn off VM) .
4) Predixy wouldn't mark turned off Redis node as fail. No log entry like this appears:
_"2018-02-21 22:18:48.555883 N Handler.cpp:231 server 192.168.10.121:6383 mark failure"_

Also if some element that should be located on turned off node will be requested, Predixy will just hang, not capable to process the MOVED command received from cluster.

II

Also currently if one of Redis nodes was just stopped as a service without turning off the server (let say, 192.168.10.121:6383 ),
Predixy will mark the node failure and will return an error on request of element located on stopped node:

192.168.10.120:7000> get sdssd444e93
(error) ERR no server connection available

I think these MOVED replies pointing to unavailable nodes should return just "(nil)", not custom error as now.

192.168.10.122:6385> get sdssd444e93
(error) MOVED 10763 192.168.10.121:6383

**Comment by fortrue** [comment]
No.I
It's a bug, I will fix it ASAP.

No.II
A custom ERR response is good choice for request to bad redis node, nil response confuse with noexists key, and SET... requests can't response nil.

**Comment by markus9203902** [comment]
@fortrue No.I - don't hesitate to ask me for any details if needed. 

No.II - I agree, failed SETs makes a sense in this case, so leaving custom error really wise way to handle such queries.

**Comment by fortrue** [comment]
@markus9203902 
commit https://github.com/joyieldInc/predixy/commit/86183a4a979c49b334d7c279454bd1fefa24a9e8 provide a new config **ServerTimeout**, it's redis server connection socket read/write timeout, to avoid wait redis response too long. For blocked requests(BLPOP...), the new config **KeepAlive** will be used.

**Comment by markus9203902** [comment]
@fortrue thank you, I'll test. 
Please clarify, is the new **KeepAlive** directive works only for blocked by Redis nature commands like BRPOP, BLPOP, BRPOPLPUSH... or something other? Is it works only on Predixy side releasing connections to it, or it releases Redis cluster after the timeout?

As I got the point, **ServerTimeout** is timeout for ALL commands, and **KeepAlive** is a setting only for BRPOP, BLPOP, BRPOPLPUSH.

**Comment by fortrue** [comment]
**ServerTimeout** for almost all commands except BRPOP, BLPOP, BRPOPLUSH, transaction and PUB/SUB. implement in application layer

**KeepAlive** apply to redis connection(socket), so it works for all commands. implement in kernel layer

The both solutions close connection between predixy and redis, **NOT** client-predixy

**Comment by markus9203902** [comment]
I approve that this bug is solved and timeout handling works good. Thank you! 
@fortrue
