### ISSUE TITLE
无故断掉

### ISSUE THREAD

**Issue by songjian0270** [joyieldInc/predixy#23]
部署在服务器上第二天发现自己断开了，怎么解呢

**Comment by fortrue** [comment]
谁和谁断开了？客户端连predixy，还是predixy连redis？

**Comment by fortrue** [comment]
可以加微信cppfan，让我看看具体情况

**Comment by fortrue** [comment]
之前predixy对信号SIGHUP的处理方式为打印堆栈然后退出，如果在终端里启动predixy，然后终端又异常退出，这时系统会主动给predixy发送SIGHUP信号导致predixy退出。
为了避免这种无谓的SIGHUP信号导致predixy退出，现在predixy修改了对SIGHUP的处理方式，改为忽略SIGHUP信号。
