### ISSUE TITLE
predixy-1.0.4 crash

### ISSUE THREAD

**Issue by cycker** [joyieldInc/predixy#29]
2018-04-18 20:31:59.024826 N Handler.cpp:212 h 3 remove c 192.168.1.3:35988 1415 with status 2 End
*** glibc detected *** ./predixy: free(): corrupted unsorted chunks: 0x00007f94207c1d10 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75e66)[0x7f943866fe66]
/lib64/libc.so.6(+0x789b3)[0x7f94386729b3]
./predixy(_ZN7Request5clearEv+0x748)[0x4b2a28]
./predixy(_ZN16AcceptConnection5writeEP7HandlerP5IOVeci+0x156e)[0x479efe]
./predixy(_ZN16AcceptConnection10writeEventEP7Handler+0x28)[0x47a708]
./predixy(_ZN7Handler25postAcceptConnectionEventEv+0x7b)[0x4cf68b]
./predixy(_ZN7Handler3runEv+0x1d0)[0x4d1c90]
./predixy[0x530db0]
/lib64/libpthread.so.0(+0x79d1)[0x7f9438e2f9d1]
/lib64/libc.so.6(clone+0x6d)[0x7f94386e28fd]
======= Memory map: ========
00400000-005be000 r-xp 00000000 08:04 2152684892                         /home/cycker/predixy-1.0.2/predixy
007bd000-007c6000 rw-p 001bd000 08:04 2152684892                         /home/cycker/predixy-1.0.2/predixy
007c6000-007c9000 rw-p 00000000 00:00 0 
0196e000-019c1000 rw-p 00000000 00:00 0                                  [heap]
7f9418000000-7f941b5f0000 rw-p 00000000 00:00 0 
7f941b5f0000-7f941c000000 ---p 00000000 00:00 0 
7f9420000000-7f9423a40000 rw-p 00000000 00:00 0 
7f9423a40000-7f9424000000 ---p 00000000 00:00 0 
7f9428000000-7f942b437000 rw-p 00000000 00:00 0 
7f942b437000-7f942c000000 ---p 00000000 00:00 0 
7f942c000000-7f942e9b0000 rw-p 00000000 00:00 0 
7f942e9b0000-7f9430000000 ---p 00000000 00:00 0 
7f9430000000-7f9430023000 rw-p 00000000 00:00 0 
7f9430023000-7f9434000000 ---p 00000000 00:00 0 
7f9435df5000-7f9435df6000 ---p 00000000 00:00 0 
7f9435df6000-7f94365f6000 rw-p 00000000 00:00 0                          [stack:32928]
7f94365f6000-7f94365f7000 ---p 00000000 00:00 0 
7f94365f7000-7f9436df7000 rw-p 00000000 00:00 0                          [stack:32927]
7f9436df7000-7f9436df8000 ---p 00000000 00:00 0 
7f9436df8000-7f94375f8000 rw-p 00000000 00:00 0                          [stack:32926]
7f94375f8000-7f94375f9000 ---p 00000000 00:00 0 
7f94375f9000-7f9437df9000 rw-p 00000000 00:00 0                          [stack:32925]
7f9437df9000-7f9437dfa000 ---p 00000000 00:00 0 
7f9437dfa000-7f94385fa000 rw-p 00000000 00:00 0                          [stack:32924]
7f94385fa000-7f9438784000 r-xp 00000000 08:04 2152333693                 /lib64/libc-2.12.so
7f9438784000-7f9438984000 ---p 0018a000 08:04 2152333693                 /lib64/libc-2.12.so
7f9438984000-7f9438988000 r--p 0018a000 08:04 2152333693                 /lib64/libc-2.12.so
7f9438988000-7f9438989000 rw-p 0018e000 08:04 2152333693                 /lib64/libc-2.12.so
7f9438989000-7f943898e000 rw-p 00000000 00:00 0 
7f943898e000-7f94389a4000 r-xp 00000000 08:04 4302589354                 /lib64/libgcc_s-4.4.6-20110824.so.1
7f94389a4000-7f9438ba3000 ---p 00016000 08:04 4302589354                 /lib64/libgcc_s-4.4.6-20110824.so.1
7f9438ba3000-7f9438ba4000 rw-p 00015000 08:04 4302589354                 /lib64/libgcc_s-4.4.6-20110824.so.1
7f9438ba4000-7f9438c27000 r-xp 00000000 08:04 2152333694                 /lib64/libm-2.12.so
7f9438c27000-7f9438e26000 ---p 00083000 08:04 2152333694                 /lib64/libm-2.12.so
7f9438e26000-7f9438e27000 r--p 00082000 08:04 2152333694                 /lib64/libm-2.12.so
7f9438e27000-7f9438e28000 rw-p 00083000 08:04 2152333694                 /lib64/libm-2.12.so
7f9438e28000-7f9438e3f000 r-xp 00000000 08:04 2152333646                 /lib64/libpthread-2.12.so
7f9438e3f000-7f943903f000 ---p 00017000 08:04 2152333646                 /lib64/libpthread-2.12.so
7f943903f000-7f9439040000 r--p 00017000 08:04 2152333646                 /lib64/libpthread-2.12.so
7f9439040000-7f9439041000 rw-p 00018000 08:04 2152333646                 /lib64/libpthread-2.12.so
7f9439041000-7f9439045000 rw-p 00000000 00:00 0 
7f9439045000-7f9439065000 r-xp 00000000 08:04 2152333638                 /lib64/ld-2.12.so
7f943922d000-7f9439254000 rw-p 00000000 00:00 0 
7f9439261000-7f9439264000 rw-p 00000000 00:00 0 
7f9439264000-7f9439265000 r--p 0001f000 08:04 2152333638                 /lib64/ld-2.12.so
7f9439265000-7f9439266000 rw-p 00020000 08:04 2152333638                 /lib64/ld-2.12.so
7f9439266000-7f9439267000 rw-p 00000000 00:00 0 
7ffc4ccc7000-7ffc4cce8000 rw-p 00000000 00:00 0                          [stack]
7ffc4cd95000-7ffc4cd96000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
2018-04-18 20:31:59.025535 E Backtrace.h:18 predixy backtrace(6)
./predixy(_Z9traceInfoi+0x114)[0x4dbe84]
./predixy[0x4dad6d]
/lib64/libc.so.6(+0x326a0)[0x7f943862c6a0]
/lib64/libc.so.6(gsignal+0x35)[0x7f943862c625]
/lib64/libc.so.6(abort+0x175)[0x7f943862de05]
/lib64/libc.so.6(+0x70537)[0x7f943866a537]
/lib64/libc.so.6(+0x75e66)[0x7f943866fe66]
/lib64/libc.so.6(+0x789b3)[0x7f94386729b3]
./predixy(_ZN7Request5clearEv+0x748)[0x4b2a28]
./predixy(_ZN16AcceptConnection5writeEP7HandlerP5IOVeci+0x156e)[0x479efe]
./predixy(_ZN16AcceptConnection10writeEventEP7Handler+0x28)[0x47a708]
./predixy(_ZN7Handler25postAcceptConnectionEventEv+0x7b)[0x4cf68b]
./predixy(_ZN7Handler3runEv+0x1d0)[0x4d1c90]
./predixy[0x530db0]
/lib64/libpthread.so.0(+0x79d1)[0x7f9438e2f9d1]
/lib64/libc.so.6(clone+0x6d)[0x7f94386e28fd]

**Comment by fortrue** [comment]
@cycker 
what happen?
