### ISSUE TITLE
Question about latency monitor

### ISSUE THREAD

**Issue by markus9203902** [joyieldInc/predixy#31]
What exact latency shows the Predixy latency? 
What measure unit it shows: microseconds or milliseconds?
I mean a TimeSpan parameters from the latency.conf. 

# LatencyMonitor
LatencyMonitorName:all
<=          100            270607384          5489974 93.80%
<=          200             36624590           283961 98.65%
<=          300              8696824            37530 99.29%
<=          400              2514521             7476 99.42%

**Comment by fortrue** [comment]
the column title
SingleRequestElapsedTimeRange(us)  RequestElapsedTimeSumInRange(us) RequestCountInRange CurrentRangeRequestsPercentForAllRequests

**Comment by markus9203902** [comment]
So us is μs = microseconds?

**Comment by fortrue** [comment]
Yes, It's microsecond.
