### ISSUE TITLE
Missing benchmark of Corvus

### ISSUE THREAD

**Issue by tevino** [joyieldInc/predixy#4]
I believe the `corvus` in the tags refers to https://github.com/eleme/corvus, if so why the name `corvus` is totally missing either in benchmark or anywhere in the documentation?

![image](https://user-images.githubusercontent.com/1027300/29953061-c556b3f4-8eff-11e7-87e6-c0e170abd515.png)

**Comment by fortrue** [comment]
Yes, the corvus is https://github.com/eleme/corvus,
I didn't know corvus when I compare predixy, twemproxy. codis and redis-cerberus.
But I had run these benckmark for corvus, the corvus slower than twemproxy a little.

**Comment by tevino** [comment]
@fortrue Could you publish the result?

**Comment by fortrue** [comment]
Done. 
https://github.com/joyieldInc/predixy/wiki/Benchmark

**Comment by tevino** [comment]
Thanks for your work.

Could you post the configurations of Corvus as well?
The value of `thread` has substantial impact on the performance.

**Comment by fortrue** [comment]
default configurations,

**Comment by tevino** [comment]
Thank you.
