### ISSUE TITLE
数据获取异常  (error) NOAUTH Authentication required.

### ISSUE THREAD

**Issue by DavenAaron** [joyieldInc/predixy#47]
-------  auth 配置----
Authority {
    Auth {
        Mode write
    }
    Auth 12312300 {
        Mode admin
    }
}

------ 错误提示-------
127.0.0.1:7617> set name daven
OK
127.0.0.1:7617> get name
(error) NOAUTH Authentication required.
127.0.0.1:7617> info
# Proxy
Version:1.0.5-pre
Name:Session
Bind:0.0.0.0:7617
RedisMode:proxy
SingleThread:false
WorkerThreads:4
Uptime:1535441754
UptimeSince:2018-08-28 15:35:54

# SystemResource
UsedMemory:139744
MaxMemory:0
MaxRSS:1933312
UsedCpuSys:0.029
UsedCpuUser:0.021

# Stats
Accept:2
ClientConnections:1
TotalRequests:116
TotalResponses:116
TotalRecvClientBytes:136
TotalSendServerBytes:2560
TotalRecvServerBytes:41024
TotalSendClientBytes:1849

# Servers
Server:127.0.0.1:6001
Role:master
Group:176dfd3a99641812449251898536fa2962e11eac
DC:
CurrentIsFail:0
Connections:3
Connect:3
Requests:16
Responses:16
SendBytes:376
RecvBytes:7566

Server:127.0.0.1:6002
Role:master
Group:77c97fc32c865d937b34ba7fab391779f9fbac59
DC:
CurrentIsFail:0
Connections:4
Connect:4
Requests:20
Responses:20
SendBytes:470
RecvBytes:8336

Server:127.0.0.1:6003
Role:master
Group:afb732990985b792baa754ec89da6d6fd1c2524b
DC:
CurrentIsFail:0
Connections:2
Connect:2
Requests:9
Responses:9
SendBytes:204
RecvBytes:3789

Server:127.0.0.1:6004
Role:slave
Group:176dfd3a99641812449251898536fa2962e11eac
DC:
CurrentIsFail:0
Connections:4
Connect:4
Requests:27
Responses:27
SendBytes:660
RecvBytes:14355

Server:127.0.0.1:6005
Role:slave
Group:afb732990985b792baa754ec89da6d6fd1c2524b
DC:
CurrentIsFail:0
Connections:3
Connect:3
Requests:14
Responses:14
SendBytes:320
RecvBytes:6060

Server:127.0.0.1:6006
Role:slave
Group:77c97fc32c865d937b34ba7fab391779f9fbac59
DC:
CurrentIsFail:0
Connections:3
Connect:9
Requests:27
Responses:27
SendBytes:530
RecvBytes:918

# LatencyMonitor
LatencyMonitorName:all
<=          100                   18                2 33.33%
<=          200                  118                1 50.00%
<=          300                  452                2 83.33%
<=          400                  303                1 100.00%
T           148                  891                6

LatencyMonitorName:get
<=          300                  452                2 100.00%
T           226                  452                2

LatencyMonitorName:set
<=          400                  303                1 100.00%
T           303                  303                1

LatencyMonitorName:blist

**Comment by DavenAaron** [comment]
###### auth #######

Authority {
    Auth {
        Mode write
    }
    Auth 12312300 {
        Mode admin
    }
}


[root@jwdtest predixy]# redis-cli -c -p 7617
127.0.0.1:7617> auth 12312300
OK
127.0.0.1:7617> get name
(error) NOAUTH Authentication required.

**Comment by fortrue** [comment]
redis-cli -p 7617 -a 12312300
这样试试

**Comment by DavenAaron** [comment]
# redis-cli -p 7617 -a 12312300
Warning: Using a password with '-a' option on the command line interface may not be safe.
127.0.0.1:7617> get name
(error) NOAUTH Authentication required.
127.0.0.1:7617>

**Comment by fortrue** [comment]
redis本身是不是设置了密码

**Comment by DavenAaron** [comment]
后边挂载的redis-cluster   没有设置密码

**Comment by DavenAaron** [comment]
]# redis-cli -c -p 6001
127.0.0.1:6001> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:1
cluster_stats_messages_ping_sent:29357
cluster_stats_messages_pong_sent:27492
cluster_stats_messages_sent:56849
cluster_stats_messages_ping_received:27492
cluster_stats_messages_pong_received:29205
cluster_stats_messages_received:56697
127.0.0.1:6001> get name
-> Redirected to slot [5798] located at 127.0.0.1:6002
"daven"
127.0.0.1:6002>

**Comment by fortrue** [comment]
什么问题？

**Comment by walk1ng** [comment]
@DavenAaron 你好，请问这个问题解决了吗？是什么情况？
