### ISSUE TITLE
centos6.5下编译各种问题

### ISSUE THREAD

**Issue by sj1385** [joyieldInc/predixy#57]
你好，由于centos6的GCC版本问题，升级成4.8+编译也不成功，但是同样的包拿到centos7上编译没有问题。
是否可以提供二进制的包，或者centos6.5上的解决方法。

[root@localhost ~]# gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# ls
anaconda-ks.cfg  devtools-2.repo  install.log  install.log.syslog  predixy-master
[root@localhost ~]# cd predixy-master/
[root@localhost predixy-master]# ls
conf  _config.yml  doc  LICENSE  Makefile  README_CN.md  README.md  src  test
[root@localhost predixy-master]# make
make[1]: Entering directory `/root/predixy-master/src'
/opt/rh/devtoolset-2/root/usr/bin/c++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Crc16.cpp 
/opt/rh/devtoolset-2/root/usr/bin/c++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c HashFunc.cpp 
/opt/rh/devtoolset-2/root/usr/bin/c++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Timer.cpp 
/opt/rh/devtoolset-2/root/usr/bin/c++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Logger.cpp 
/opt/rh/devtoolset-2/root/usr/bin/c++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c LogFileSink.cpp 
/opt/rh/devtoolset-2/root/usr/bin/c++ -std=c++11 -Wall -w -g -O3 -D_PREDIXY_BACKTRACE_ -D_EPOLL_ -c Alloc.cpp 
Alloc.cpp: In function ‘int& _ZTWN5AllocIT_XT0_EE4SizeE()’:
Alloc.cpp:10:36: internal compiler error: in var_defined_without_dynamic_init, at cp/decl2.c:2811
 AtomicLong AllocBase::UsedMemory(0);
                                    ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccnvCPIf.out file, please attach this to your bugreport.
make[1]: *** [Alloc.o] 错误 1
make[1]: Leaving directory `/root/predixy-master/src'
make: *** [default] 错误 2

**Comment by fortrue** [comment]
在CentOS6上GCC升级到4.9，我抽空传一下二进制

**Comment by fortrue** [comment]
已添加二进制包，见releases页面
