### ISSUE TITLE
不支持flushdb、dbsize等命令

### ISSUE THREAD

**Issue by Eggache666** [joyieldInc/predixy#58]
redis客户端单连集群中的某个节点，支持flushdb命令，但不影响其他节点。若要每个都清空，得一个一个清空，甚是麻烦。能否支持flushdb命令，全部清除？
像这些集群中单个节点支持的命令，比如dbsize、keys……，后续能否得到支持？

**Comment by fortrue** [comment]
predixy作为一个代理，不会去支持这些命令，可以使用我们的[rediser](https://github.com/joyieldInc/rediser)工具

**Comment by Eggache666** [comment]
如果要获取某一类的键值，不能用keys命令，该如何获得这一组数据呢？

**Comment by fortrue** [comment]
keys很危险，不要使用，用scan代替

**Comment by Eggache666** [comment]
好的，谢谢！
