### ISSUE TITLE
无法用del命令删除key

### ISSUE THREAD

**Issue by hyqf** [joyieldInc/predixy#6]
删除key ,这个要指定key的值，操作起来不方便
172.16.11.43:7617> set test 123
OK
172.16.11.43:7617> get test
"123"
172.16.11.43:7617> del test
(error) ERR unknown command '$4'

**Comment by fortrue** [comment]
这是个bug，del是个多key命令，结果在只有一个key的时候parse有bug，已修复，见https://github.com/joyieldInc/predixy/commit/017ae6461b285fb83d4c48935a28ff814a929d84

**Comment by fortrue** [comment]
已发布新版本，此问题解决
https://github.com/joyieldInc/predixy/releases/tag/1.0.2
