### ISSUE TITLE
Feature request: server reload

### ISSUE THREAD

**Issue by mosquito** [joyieldInc/predixy#66]
We are using predixy as a redis proxy and we are satisfied.

But in case when redis server IP address changing but server's DNS is not changing we are have to restart predixy for applying a new configuration.

It's just one a simple case when predixy needs to restart, but we are want to do it convenient, e.g. by sending a HUP signal to the process for reread configuration files and reload when success.

**Comment by jeremyxu2010** [comment]
我也遇到这个问题，我们是将predixy部署到容器的，在predixy的配置文件里配置的是redis集群的service name(相当于dns名)，当service name指向的pod ip发生变化时，predixy并没有感知，感下面这个配置并没有发生的作用

**Comment by gitbotsman** [comment]
我也遇到同样的问题，公司做高可用改造，原来的IP改成域名，当redis故障域名解析IP切换后，predixy依旧请求故障中redis

**Comment by amilytan** [comment]
> 我也遇到这个问题，我们是将predixy部署到容器的，在predixy的配置文件里配置的是redis集群的service name(相当于dns名)，当service name指向的service ip发生变化时，predixy并没有感知，感下面这个配置并没有发生的作用
> 
> `RefreshInterval: predixy会周期性的请求redis sentinel以获取最新的集群信息，该参数以秒为单位指定刷新周期，不指定的话为1秒`
> 
> @fortrue

请问这个问题解决了吗
