### ISSUE TITLE
about thread-safe

### ISSUE THREAD

**Issue by IronsDu** [joyieldInc/predixy#7]
Can you push some document about predixy's design?
I read your code, but still don't know your design, I worry not thread-safe when push request to backend from multi client and push multi response to client from different backend redis . and either merge multi reply, then send to client.

有一些整体设计的文档么？
我简单看了下代码，还没搞懂你的设计，我不知道是否存在线程安全问题：
1、当从不同客户端读取到请求然后转发给某一个redis 后端时，如果此redis后端链接和clien他不在同一个Handler线程。 
2、当从多个redis后端收到reply，这些reply属于同一个client时，怎么将reply（线程安全的）告诉client 。
3、 来自client的某个request可能涉及到多个redis后端进行处理，那么收到后者的reply之后是否存在merge处理？
4、当一个client存在多个pending的请求：A、B、C。 如果他们分别被不同的redis 后端处理，那么当B对应redis server先处理完毕，它的reply先返回，是否考虑了顺序问题（也就是等B之前的请求，也就是A完成了才能将B告诉client）？

**Comment by fortrue** [comment]
每个handler是一个处理线程，每个handler与后端redis连接都是独立的，每个client连接永远都只会在一个handler里处理。用多进程模型来对比的话，每个handler就好比一个独立的进程，在处理请求和响应的时候各handler之间完全没有任何关系。当然handler之间还是有一些共享的东西，主要就是后端redis的节点信息，所以在更新这些信息的时候需要加锁。
所以你提到的问题1、2在predixy里不会跨线程，问题3、4，正常的代理都必须正确处理

**Comment by IronsDu** [comment]
哦哦，明白。类似单线程多进程。
