### ISSUE TITLE
redis

### ISSUE THREAD

**Issue by kangjianhua** [joyieldInc/predixy#8]

**Comment by kangjianhua** [comment]
后端使用redis 4.0 版本，是否做个稳定性压测？

**Comment by fortrue** [comment]
redis 4.0的话，目前module功能还未支持，另一个最大的差异是redis cluster模式下cluster nodes返回结果格式变了，这个已经支持。稳定性压测用以下命令可测：

    redis-benchmark -p 7617 -l
