### ISSUE TITLE
predixy 是否支持cluster命令

### ISSUE THREAD

**Issue by caipengtao** [joyieldInc/predixy#9]
如题

**Comment by fortrue** [comment]
作为redis cluster的代理是predixy的一大功能，predixy自身通过cluster nodes命令来发现redis cluster信息，但是predixy不对client提供cluster命令支持，因为有了predixy之后，client直接连predixy用就好，无需考虑具体的redis cluster实例节点信息。

**Comment by caipengtao** [comment]
我们使用erlang的程序去连接predixy的时候报错。。。
2> eredis:start_link("172.16.100.11",7617, 0, "ptwrite").
** exception exit: {authentication_error,{unexpected_data,{ok,<<"-ERR unknown command 'auth'\r\n">>}}}

**Comment by caipengtao** [comment]
我们使用erlang连接predixy的时候报错。。。
2> eredis:start_link("192.168.100.11",7617, 0, "testwrite").
** exception exit: {authentication_error,{unexpected_data,{ok,<<"-ERR unknown command 'auth'\r\n">>}}}

**Comment by fortrue** [comment]
查了一下这个问题，这是因为eredis发送AUTH命令的时候用的是redis命令协议的inline command格式，predixy目前不支持这种格式。

    [pid 17562] writev(10, [{NULL, 0}, {"AUTH \"readonly\"\r\n", 17}], 2) = 17

redis请求协议响应格式说明可以参见https://redis.io/topics/protocol。

**Comment by fortrue** [comment]
已修改支持AUTH命令通过inline command协议发送
https://github.com/joyieldInc/predixy/commit/345ff2c20f6ebdd1f7b55edb7e70b15381eceae2
