### ISSUE TITLE
不支持config set notify-keyspace-events Egx 命令

### ISSUE THREAD

**Issue by shuixianmu** [joyieldInc/predixy#93]
predixy不支持config set notify-keyspace-events 命令。

连接preixy执行该命令报参数错误，连接redis集群的任意主节点执行该命令无报错

![image](https://user-images.githubusercontent.com/25890410/67910399-80cfbf00-fbbd-11e9-9653-e2dfccffd8c7.png)

**Comment by fortrue** [comment]
predixy是一个代理，主要是用于业务命令的，这类运维管理命令不支持

**Comment by shuixianmu** [comment]
OK。谢谢

**Comment by 40kuai** [comment]
xiexie
